Exclude 3 more Q-ids from the default query
Nudin/makesense pull request #35
Opened 2020-05-04 14:02 UTC by swedebugia

These were present when I looked through swedish senses today

2020-05-05 00:20 UTC, Nudin requested changes
See my two inline comments.
But an even bigger issue is, that the query times out when adding these 5 additional rules. :/ Even without them the query sometimes timeouts. Interestingly it doesn't timeout (35s/50s) when the filter for the english language isn't included. We could remove that and filter the results ourself in python – but this sounds as if the query could be optimized. I'm not good at query-optimization though. Maybe @lucaswerkmeister can help?

2020-05-05 00:20 UTC, Nudin commented on queries/default.sparql
> +                Q7397
The prefixes (`wd:`) are missing.

2020-05-05 00:20 UTC, Nudin commented on queries/default.sparql
> +                # software
We might want to either add a comment to all items (preferred) or to none.

2020-05-09 00:19 UTC, Nudin commented
I managed to optimize the query enough to add a bigger list of false-positives I joined your list together with the list provided by @so9q to get rid of a lot of wrong matches!
Thanks for providing the list! It is merged and deployed now.

2020-05-09 00:19 UTC, closed without merging

2020-05-09 15:49 UTC, lucaswerkmeister commented
You could try changing `FILTER NOT EXISTS` to `MINUS`, that’s often faster and should be equivalent here.